import 'dart:ui';

final List<Map<String, String>> struggleData = [
  {
    "title": "I want a simple daily ritual to take care of my mind",
    "struggle_tag": "ritual",
    "message":
        "Small structured rituals are the easiest way to feel better consistently. Panda will make it simple.",
  },
  {
    "title": "I want to feel grateful and more present",
    "struggle_tag": "positive",
    "message":
        "Your intention is already strong. Panda will guide you, one gentle moment a day.",
  },
  {
    "title": "I feel anxious or overwhelmed",
    "struggle_tag": "anxious",
    "message":
        "Sometimes your mind and body feel like they are always on alert. You deserve simple grounding, not pressure.",
  },
  {
    "title": "My mind never stops racing",
    "struggle_tag": "racing",
    "message":
        "Even in quiet moments, your thoughts keep running. You need gentle rituals that help your mind slow down, not force it.",
  },
  {
    "title": "I keep trying gratitude journaling but it never sticks.",
    "struggle_tag": "journaling",
    "message":
        "Blank pages cannot teach gratitude. You were never the problem. You just needed gentle structure.",
  },
  {
    "title": "I feel numb or disconnected",
    "struggle_tag": "numb",
    "message":
        "Feeling nothing is not failure. It is your nervous system protecting you. You just need small moments to reconnect.",
  },
  {
    "title": "I always notice what’s wrong instead of what’s good",
    "struggle_tag": "comparison",
    "message":
        "Your mind has been stuck in protection mode. With small reframes, you can slowly shift toward what is working.",
  },
  {
    "title": "I feel tired and burnt out",
    "struggle_tag": "burnout",
    "message":
        "When everything feels like effort, you need rituals that give energy, not drain it.",
  },
];

final List<String> nameSuggestions = [
  'Momo',
  'Lumi',
  'Nori',
  'Koko',
  'Rumi',
  'Sumi',
  'Tali',
  'Kipi',
  'Poko',
  'Luno',
  'Zuri',
  'Neko',
  'Pumi',
  'Lilo',
  'Miso',
  'Sato',
  'Zuzu',
  'Taro',
  'Miro',
];

final List<Map<String, dynamic>> proBenefits = [
  {
    'icon': 'assets/probenefits1.png',
    'title': 'No ads',
    'description': 'Enjoy a clean, calm experience without interruptions.',
  },
  {
    'icon': 'assets/probenefits2.png',
    'title': 'Data backup',
    'description':
        'Your entries, images, audio, and boards are securely backed up so you never lose your progress or moments.',
  },
  {
    'icon': 'assets/probenefits3.png',
    'title': 'Attach unlimited images',
    'description':
        'Add as many photos as you want to your gratitude entries so you can remember moments more vividly.',
  },
  {
    'icon': 'assets/probenefits4.png',
    'title': 'Record unlimited audio',
    'description':
        'Speak your thoughts freely. Voice notes capture emotion in a way typing can’t.',
  },
  {
    'icon': 'assets/probenefits5.png',
    'title': 'Custom dates for your journal',
    'description':
        'Fill in missed days or reflect on past moments without restrictions.',
  },
  {
    'icon': 'assets/probenefits6.png',
    'title': 'Access all affirmations',
    'description':
        'Explore every category and find the exact words you need for your mood.',
  },
  {
    'icon': 'assets/probenefits7.png',
    'title': 'Create unlimited vision boards',
    'description':
        'Build as many boards as you want to stay inspired and focused on your goals.',
  },
];

final List<Map<String, String>> cardContents = [
  {
    'title': 'Pro Users Grow Faster',
    'description':
        'Get unlimited gratitude, full affirmation access, and advanced tools that support your growth journey.',
    'image': 'assets/RightSideFilledArrow.png',
  },
  {
    'title': 'App Update is Required',
    'description':
        'Automatically back up or load from the Grateful panda cloud.',
    'image': 'assets/RightSideFilledArrow.png',
  },
  {
    'title': 'Data Backups',
    'description':
        'Keep your progress safe. Enable cloud backups so your panda and rituals stay with you everywhere.',
    'image': 'assets/RightSideFilledArrow.png',
  },
  {
    'title': 'Your Mind Rewires in 21 Days',
    'description':
        'A small daily reminder helps your brain form a steady gratitude habit that supports your mood and emotional balance.',
    'image': 'assets/RightSideFilledArrow.png',
  },
];

final List<String> monthNames = [
  "",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

String getMonthName(int month) => monthNames[month];

// ignore: non_constant_identifier_names
final List<Map<String, String>> FAQDict = [
  {
    "question": "What is Grateful Panda and how does it work?",
    "answer":
        "Grateful Panda is a daily mental wellness app that helps you feel better through simple gratitude and reflection rituals. Each day, you complete short guided reflections, and as you show up consistently, your Panda grows, turning an invisible habit into visible progress that motivates you to keep going.",
  },
  {
    "question": "Is Grateful Panda a meditation app or something else?",
    "answer":
        "Grateful Panda is not a meditation app. It is a daily gratitude and reflection app designed to help you feel calmer and more grounded without long sessions, silence, spiritual language, or pressure to clear your mind.",
  },
  {
    "question": "What makes Grateful Panda different from journaling apps?",
    "answer":
        "Grateful Panda removes the hardest part of journaling, knowing what to write and staying consistent. Instead of blank pages, it gives you short guided prompts and turns your consistency into visible progress through your Panda’s growth.",
  },
  {
    "question": "How is Grateful Panda different from meditation apps?",
    "answer":
        "Grateful Panda does not ask you to meditate or clear your thoughts. Instead of long sessions, it uses short guided rituals that fit into real life and help you feel calmer through consistency rather than discipline.",
  },
  {
    "question": "Is Grateful Panda just another self help app?",
    "answer":
        "No. Grateful Panda is a quiet and gentle space for daily reflection. It focuses on showing up rather than fixing yourself, and it avoids loud motivation, pressure, or unrealistic promises.",
  },
  {
    "question": "Is Grateful Panda for people who feel stuck or unmotivated?",
    "answer":
        "Yes. Grateful Panda is especially helpful for people who feel stuck, unmotivated, or mentally drained. It helps you start small so you can rebuild momentum without overwhelm or pressure.",
  },
  {
    "question":
        "Is Grateful Panda good for busy people who don’t have time to journal?",
    "answer":
        "Yes. Grateful Panda is designed for busy people. It takes just a few minutes a day and does not require long writing or a big time commitment.",
  },
  {
    "question": "Is there an app for people who overthink but want peace?",
    "answer":
        "Yes. Grateful Panda is made for people who overthink but want peace. It gently slows your thoughts through simple daily reflection rituals without forcing meditation or big life changes.",
  },
  {
    "question": "Is Grateful Panda good for anxiety or low moods?",
    "answer":
        "Yes. Grateful Panda can be helpful for anxiety and low moods. It does not try to fix you but gently grounds your thoughts, helping reduce overthinking and making difficult days feel more manageable.",
  },
  {
    "question": "Is gratitude actually useful or just fake positivity?",
    "answer":
        "Gratitude is not fake positivity when it is done honestly. Grateful Panda does not force happiness. It helps you notice small real things that ground you and slowly shift how you feel over time.",
  },
  {
    "question": "Does gratitude work if your life isn’t great?",
    "answer":
        "Yes. Gratitude can work even when life is not great. Grateful Panda does not ask you to pretend everything is fine. It helps you hold onto small real moments so hard days feel a little lighter.",
  },
  {
    "question": "Do I need to believe in gratitude for this to work?",
    "answer":
        "No. You do not need to believe in anything for Grateful Panda to work. You can be skeptical or unsure. The app simply guides you to reflect honestly.",
  },
  {
    "question": "Is this okay to use when I’m not feeling positive?",
    "answer":
        "Yes. Grateful Panda is designed for real days, including bad ones. You are never asked to force positivity or hide how you feel.",
  },
  {
    "question": "How much time does Grateful Panda take each day?",
    "answer":
        "Most people complete their daily rituals in under five minutes. You can spend more time if you want, but it is never required.",
  },
  {
    "question": "What if I miss a day?",
    "answer":
        "Nothing bad happens. There is no punishment, guilt, or streak pressure. You simply continue whenever you are ready.",
  },
  {
    "question": "Do I have to write a lot?",
    "answer":
        "No. Your responses can be short and simple. You can write as little or as much as you want.",
  },
  {
    "question": "Why does the Panda grow?",
    "answer":
        "The Panda grows to make consistency visible. Each time you show up, your effort is reflected back to you so you can see your progress over time.",
  },
  {
    "question": "What happens if I stop using the app?",
    "answer":
        "Your Panda simply pauses. It does not shrink or punish you. Growth continues when you return.",
  },
  {
    "question": "Is the Panda just decorative?",
    "answer":
        "No. The Panda represents your consistency and care. It is a visual reminder that small daily actions matter.",
  },
  {
    "question": "What kind of people use Grateful Panda?",
    "answer":
        "Grateful Panda is used by people who feel mentally tired, overthink often, or want to feel better without pressure. This includes busy professionals, creatives, students, and anyone looking for calm and emotional balance.",
  },
  {
    "question": "What’s a simple daily ritual for feeling grounded?",
    "answer":
        "A simple daily ritual is pausing to notice a few real things you are grateful for. Grateful Panda guides you through this in just a few minutes each day.",
  },
  {
    "question": "What’s the easiest way to practice gratitude daily?",
    "answer":
        "The easiest way is to keep it small and guided. Grateful Panda helps you practice gratitude without overthinking by giving you simple prompts you can complete quickly.",
  },
  {
    "question": "Is Grateful Panda a replacement for therapy?",
    "answer":
        "No. Grateful Panda is a self reflection and mental wellness tool. It can support your well being but does not replace professional care.",
  },
  {
    "question": "Is this app clinical or diagnostic?",
    "answer":
        "No. Grateful Panda avoids diagnoses, labels, and clinical language. It focuses on everyday emotional well being.",
  },
  {
    "question": "Is my data private?",
    "answer":
        "Your reflections are personal. Grateful Panda is designed to respect your privacy and keep your thoughts safe.",
  },
  {
    "question": "When will I start feeling a difference?",
    "answer":
        "Many people notice subtle changes within days. Bigger changes usually come from consistency over time.",
  },
  {
    "question": "What if this feels too simple?",
    "answer":
        "Simple is intentional. Small consistent actions are easier to maintain and often more effective than trying to change everything at once.",
  },
  {
    "question": "Who is Grateful Panda not for?",
    "answer":
        "If you are looking for intensive therapy, long meditation sessions, or productivity tracking, Grateful Panda may not be the right fit.",
  },
];

final List<Map<String, String>> introTextArray = [
  {
    "text": "Settle into a comfortable position",
    "audio_male": "audio/settle-male.mp3",
    "audio_female": "audio/settle-female.mp3",
  },
  {
    "text": "Take a gentle breath in…",
    "audio_male": "audio/breath-in-male.mp3",
    "audio_female": "audio/breath-in-female.mp3",
  },
  {
    "text": "And a slow breath out.",
    "audio_male": "audio/breath-out-male.mp3",
    "audio_female": "audio/breath-out-female.mp3",
  },
  {
    "text": "Let’s begin.",
    "audio_male": "audio/begin-male.mp3",
    "audio_female": "audio/begin-female.mp3",
  },
];

final List<Map<String, dynamic>> musicList = [
  {"audio": "assets/audio/close-eyes.mp3", "title": "Close eyes"},
  {"audio": "assets/audio/creation.mp3", "title": "Creation"},
  {"audio": "assets/audio/crossing-sea.mp3", "title": "Crossing sea"},
  {"audio": "assets/audio/deep.mp3", "title": "Deep"},
  {"audio": "assets/audio/explore.mp3", "title": "Explore"},
  {"audio": "assets/audio/floating-on-cloud.mp3", "title": "Floating on cloud"},
  {"audio": "assets/audio/healing-spirit.mp3", "title": "Healing spirit"},
  {"audio": "assets/audio/inner-peace.mp3", "title": "Inner peace"},
  {"audio": "assets/audio/magic-trails.mp3", "title": "Magic trails"},
  {"audio": "assets/audio/morning-blossom.mp3", "title": "Morning blossom"},
  {"audio": "assets/audio/oasis.mp3", "title": "Oasis"},
  {"audio": "assets/audio/purity-forest.mp3", "title": "Purity forest"},
  {"audio": "assets/audio/rising-sun.mp3", "title": "Rising sun"},
  {"audio": "assets/audio/safe-shores.mp3", "title": "Safe shores"},
  {"audio": "assets/audio/sound-of-stars.mp3", "title": "Sound of stars"},
  {"audio": "assets/audio/sweet-moonlight.mp3", "title": "Sweet moonlight"},
  {"audio": "assets/audio/vision.mp3", "title": "Vision"},
  {"audio": "aassets/udio/whispering-forest.mp3", "title": "Whispering forest"},
  {"audio": "assets/audio/world-awaits.mp3", "title": "World awaits"},
];

final List<Map<String, dynamic>> categories = [
  {
    "isPremium": "1",
    "category": "Grounded Mind",
    "index": 1,
    "image": 'assets/grounded_mind.png',
    "affirmations": [
      "I am steady, even when life moves around me",
      "I return to the present moment whenever my thoughts wander.",
      "I can handle what’s in front of me, one thing at a time.",
      "My mind knows how to slow down and find peace.",
      "I am grounded in what is real, not what I imagine.",
      "Each breath reminds me that I am safe here and now",
      "I don’t need to control everything to feel secure.",
      "I can rest inside the calm space of my own awareness.",
      "My thoughts come and go like gentle waves — I stay centered beneath them.",
    ],
  },
  {
    "isPremium": "0",
    "category": "Peaceful Body",
    "index": 2,
    "image": 'assets/peaceful_body.png',
    "affirmations": [
      "I listen to my body with patience and respect.",
      "My body deserves kindness, not criticism.",
      "I release tension with every slow, mindful breath.",
      "I am learning to feel safe inside my own skin.",
      "My body is my home — I treat it with softness.",
      "Relaxation is not laziness; it is recovery.",
      "I let my shoulders drop and my jaw unclench — peace begins here.",
      "I thank my body for carrying me through each day.",
      "Stillness restores me in ways effort never can.",
    ],
  },
  {
    "isPremium": "0",
    "category": "Slow Mornings",
    "index": 3,
    "image": 'assets/slow_ mornings.png',
    "affirmations": [
      "I allow my day to begin gently, without rush or guilt.",
      "I don’t need to chase the morning; I can flow with it.",
      "Calm beginnings create calm days.",
      "My first thoughts shape my energy — I choose peace.",
      "I am allowed to take my time waking into the world.",
      "Slowness is not weakness; it is wisdom.",
      "I greet this morning as an old friend — softly, with gratitude.",
      "Even a small moment of stillness can set the tone for my whole day.",
      "I deserve mornings that feel kind and unhurried.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Breath & Awareness",
    "index": 4,
    "image": 'assets/breath_awareness.png',
    "affirmations": [
      "My breath is my anchor — it brings me home to now.",
      "Each inhale nourishes me; each exhale releases what I don’t need.",
      "I am connected to life through the rhythm of my breathing.",
      "I don’t have to fix my breath; I just have to notice it.",
      "Awareness begins with something as simple as one slow inhale.",
      "When I breathe with intention, my whole body softens.",
      "I can return to calm in any moment by returning to my breath.",
      "The quiet between breaths reminds me of the stillness within me.",
      "I breathe in ease; I breathe out tension.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Strength & Courage",
    "index": 5,
    "image": 'assets/strength_courage.png',
    "affirmations": [
      "I am stronger than I remember and braver than I realize.",
      "Courage does not mean the absence of fear — it means moving with it.",
      "Every small act of effort strengthens my resilience.",
      "I trust myself to face what comes my way.",
      "Each challenge teaches me what I’m capable of.",
      "I can bend without breaking.",
      "My strength grows quietly, moment by moment.",
      "I have made it through difficult days before — I can do it again.",
      "Fear is just energy waiting to become action.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Trust in Process",
    "index": 6,
    "image": 'assets/trust_in_process.png',
    "affirmations": [
      "I release the need to rush; life unfolds in its own rhythm.",
      "Not everything needs to be solved today.",
      "I am learning to trust the pace of my growth.",
      "Every delay may carry a hidden blessing.",
      "I am not behind — I am exactly where I need to be.",
      "Patience is my quiet form of strength.",
      "I choose faith in the process over fear of the unknown.",
      "What’s meant for me will find me when I’m ready.",
      "Progress often looks like stillness before movement.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Adaptability",
    "index": 7,
    "image": 'assets/adaptability.png',
    "affirmations": [
      "I am flexible and open to change.",
      "When plans shift, I find my balance again.",
      "Change invites me to discover new parts of myself.",
      "I can adjust without losing my center.",
      "Every adaptation makes me wiser and more capable.",
      "I flow with life instead of resisting it.",
      "I welcome change as a teacher, not a threat.",
      "Flexibility keeps me growing and alive.",
      "I am grounded enough to bend, not break.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Boundaries & Balance",
    "index": 8,
    "image": 'assets/boundaries_balance.png',
    "affirmations": [
      "Saying no is an act of self-respect.",
      "My time and energy are valuable resources.",
      "I can care for others without losing myself.",
      "Balance is not perfection — it’s presence.",
      "Boundaries protect the peace I’m building.",
      "I honor my needs without guilt.",
      "Rest and solitude are part of my wellbeing.",
      "I can pause before I say yes to ensure it aligns with my values.",
      "Maintaining balance allows me to give from fullness, not exhaustion.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Letting Go",
    "index": 9,
    "image": 'assets/letting_go.png',
    "affirmations": [
      "I release what I can’t control and make space for peace.",
      "Not everything deserves my energy — I can let some things pass.",
      "Holding on is heavy; I choose lightness instead.",
      "I am learning to forgive the past and move forward with ease.",
      "Letting go is not losing — it’s trusting life to hold me.",
      "I breathe out old stories that no longer serve me.",
      "What’s meant to stay will stay; what’s meant to go will go.",
      "I can release without resentment.",
      "I honor endings as sacred parts of growth.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Forgive Self",
    "index": 10,
    "image": 'assets/forgive_self.png',
    "affirmations": [
      "I forgive myself for not knowing better at the time.",
      "Forgiveness frees me more than it frees others.",
      "I can hold compassion for my own past mistakes.",
      "I don’t need closure from others to choose peace for myself.",
      "I am no longer carrying what hurt me.",
      "Forgiveness is a gift I give to my own heart.",
      "I can understand without excusing.",
      "Releasing resentment makes room for love.",
      "Every act of forgiveness is an act of courage.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Recovery & Rest",
    "index": 11,
    "image": 'assets/recovery_rest.png',
    "affirmations": [
      "Rest is part of my healing, not a pause from it.",
      "I give myself permission to slow down and recover fully.",
      "My worth is not measured by my productivity.",
      "Healing takes time, and that time is sacred.",
      "Every breath of rest rebuilds my strength.",
      "It’s okay to need stillness after the storm.",
      "My body and mind know how to repair themselves when I allow it.",
      "Peace grows in the spaces I allow myself to pause.",
      "Today, I choose restoration over resistance.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Faith & Surrender",
    "index": 12,
    "image": 'assets/faith_surrender.png',
    "affirmations": [
      "I trust that life has a rhythm beyond my understanding.",
      "I am guided, even when I can’t see the path ahead.",
      "Uncertainty is not danger — it’s an invitation to trust.",
      "I release the need to know how everything will unfold.",
      "Faith begins where control ends.",
      "Surrender is not giving up; it’s opening up.",
      "I believe that good can arise even from the unknown.",
      "Each day, I choose to lean into trust rather than tension.",
      "I am held by something larger than my worries.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Hope & Possibility",
    "index": 13,
    "image": 'assets/hope_possibility.png',
    "affirmations": [
      "I believe in the quiet potential of each new day.",
      "Even the smallest light can guide me forward.",
      "Hope is not naïve — it’s the seed of all change.",
      "Possibility exists in places I haven’t yet looked.",
      "I allow myself to imagine a gentler future.",
      "My heart is open to what could be.",
      "Every ending carries the spark of a beginning.",
      "I trust that tomorrow can hold something beautiful.",
      "I am becoming someone who sees what’s possible, not just what’s missing.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Purpose & Meaning",
    "index": 14,
    "image": 'assets/purpose_meaning.png',
    "affirmations": [
      "I am guided by values, not just goals.",
      "Meaning grows when I give attention to what matters most.",
      "I don’t have to know my purpose — I can live into it slowly.",
      "Each small act of integrity builds a purposeful life.",
      "What I do with love becomes meaningful, no matter how small.",
      "I find meaning in being, not just achieving.",
      "My purpose is not fixed — it evolves as I do.",
      "Even ordinary days can hold extraordinary meaning.",
      "I am aligned with what feels true and right to me.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Work & Contribution",
    "index": 15,
    "image": 'assets/work_contribution.png',
    "affirmations": [
      "My work is an expression of my values, not my worth.",
      "I contribute in ways that feel authentic to who I am.",
      "Progress matters more than perfection.",
      "I am proud of the effort I give, even when results take time.",
      "The world benefits from my unique skills and care.",
      "I can work with intention without losing my balance.",
      "What I build today can serve others tomorrow.",
      "Contribution brings connection — I am part of something larger.",
      "Purposeful work fills me with quiet satisfaction.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Money & Stability",
    "index": 16,
    "image": 'assets/money_stability.png',
    "affirmations": [
      "I welcome financial stability with gratitude and wisdom.",
      "Money is a tool for peace, not pressure.",
      "I am learning to manage resources with calm and clarity.",
      "Abundance grows from responsibility and gratitude combined.",
      "I am capable of creating a secure foundation for myself.",
      "Wealth can coexist with mindfulness and compassion.",
      "I attract opportunities aligned with balance and integrity.",
      "Having enough is a feeling I nurture daily.",
      "I trust that I can sustain myself through both flow and rest.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Focus & Discipline",
    "index": 17,
    "image": 'assets/focus_discipline.png',
    "affirmations": [
      "I give my full attention to what truly matters.",
      "Discipline is a form of self-respect, not punishment.",
      "Each focused moment moves me closer to my intentions.",
      "I can stay consistent without being rigid.",
      "Progress comes from small steps done with care.",
      "My focus deepens when I remove what doesn’t serve me.",
      "I am capable of steady effort, one task at a time.",
      "Structure brings me freedom to create and grow.",
      "I am proud of the focus I bring to this moment.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Momentum & Action",
    "index": 18,
    "image": 'assets/momentum_action.png',
    "affirmations": [
      "I turn ideas into motion through simple, steady steps.",
      "Action builds confidence faster than waiting for perfection.",
      "Each small effort compounds into meaningful change.",
      "Momentum starts when I take the first small step.",
      "I am capable of turning intention into movement.",
      "Energy flows where my attention goes.",
      "Consistency is my quiet superpower.",
      "Even imperfect action moves me forward.",
      "I trust my ability to keep going, even slowly.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Creativity & Play",
    "index": 19,
    "image": 'assets/creativity_play.png',
    "affirmations": [
      "I allow curiosity to guide my creativity.",
      "Playfulness keeps my ideas alive and fresh.",
      "I don’t need to be perfect to create something beautiful.",
      "I explore without judgment and learn through joy.",
      "My creativity flows best when I stay open and relaxed.",
      "I am a vessel for inspiration — it moves through me freely.",
      "Making something new brings me closer to myself.",
      "Play is not a waste of time; it’s the source of renewal.",
      "Every creative act reconnects me with wonder.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Learning & Curiosity",
    "index": 20,
    "image": 'assets/learning_curiosity.png',
    "affirmations": [
      "I am a lifelong learner, always evolving.",
      "Curiosity is the bridge between who I am and who I can become.",
      "Each mistake teaches me something valuable.",
      "I welcome feedback as a tool for growth, not judgment.",
      "My mind expands when I stay curious and kind.",
      "Learning keeps me humble and alive.",
      "I can explore new ideas without fear of failure.",
      "Curiosity helps me see life as an unfolding adventure.",
      "I am grateful for every lesson experience brings.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Acceptance",
    "index": 21,
    "image": 'assets/acceptance.png',
    "affirmations": [
      "I accept myself completely, even as I continue to grow.",
      "I release the need to fight what already is.",
      "Peace begins the moment I stop resisting reality.",
      "I can hold both progress and imperfection at once.",
      "Acceptance does not mean giving up — it means seeing clearly.",
      "I am learning to make peace with what I cannot change.",
      "My heart softens when I let things be as they are.",
      "Every moment is easier when I meet it without judgment.",
      "I trust that acceptance creates the space for healing.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Contentment",
    "index": 22,
    "image": 'assets/contentment.png',
    "affirmations": [
      "I have enough, I do enough, I am enough.",
      "Joy often lives in ordinary moments — I choose to notice them.",
      "I don’t need more to feel complete right now.",
      "Gratitude turns what I have into abundance.",
      "I allow myself to rest in the satisfaction of the present.",
      "Peace grows where comparison fades.",
      "Contentment is not settling — it’s recognizing wholeness.",
      "I am fulfilled by the simple blessings of today.",
      "Enoughness feels calm, not loud.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Home & Sanctuary",
    "index": 23,
    "image": 'assets/home_sanctuary.png',
    "affirmations": [
      "My surroundings reflect the peace I nurture within.",
      "I create spaces that make me feel safe and at ease.",
      "Home is not just a place — it’s a feeling I can return to anytime.",
      "I deserve a space that supports my rest and renewal.",
      "I can bring calm energy wherever I go.",
      "My body and mind are my truest home.",
      "I protect my environment from chaos and negativity.",
      "Simplicity and warmth make any space sacred.",
      "I feel grounded in the sanctuary I build for myself.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Inner Stillness",
    "index": 24,
    "image": 'assets/inner_stillness.png',
    "affirmations": [
      "Beneath the noise of life, I can always find quiet.",
      "Stillness is not emptiness — it is presence.",
      "I don’t have to chase peace; I can return to it within me.",
      "Silence holds wisdom that words can’t reach.",
      "I am comfortable in moments of pause.",
      "Stillness restores my energy and clarity.",
      "I can rest in awareness without needing to change anything.",
      "Calm is my natural state beneath the surface of thought.",
      "I am whole, peaceful, and complete in this moment of stillness.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Love for Self",
    "index": 25,
    "image": 'assets/love_for_self.png',
    "affirmations": [
      "I treat myself with the same kindness I offer others.",
      "I am worthy of love without conditions or achievements.",
      "My flaws are part of my humanity, not my failure.",
      "Self-love is not vanity — it’s emotional nourishment.",
      "I speak to myself gently, like someone I care about deeply.",
      "I allow myself to take up space and exist fully.",
      "I am enough even when I’m resting, healing, or uncertain.",
      "I forgive myself for the ways I’ve abandoned my own needs.",
      "Loving myself makes it easier to love the world around me.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Love for Others",
    "index": 26,
    "image": 'assets/love_for_others.png',
    "affirmations": [
      "I see the good in others without needing them to be perfect.",
      "Kindness costs me nothing but changes everything.",
      "I can hold space for others while staying centered in myself.",
      "Every act of love expands the peace within me.",
      "Connection is built through empathy, not agreement.",
      "I choose compassion over judgment whenever I can.",
      "I am grateful for the people who share moments of life with me.",
      "Love grows stronger when I allow it to be simple.",
      "Every gesture of care ripples outward in unseen ways.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Friendship & Bonds",
    "index": 27,
    "image": 'assets/friendship_bonds.png',
    "affirmations": [
      "True friendship feels like being understood without explanation.",
      "I value the people who show up with consistency, not perfection.",
      "I can be both supported and supportive in my relationships.",
      "I nurture my friendships with honesty and warmth.",
      "Laughter and shared memories strengthen my heart.",
      "Distance can’t erase genuine connection.",
      "I appreciate those who bring lightness to my life.",
      "Every bond teaches me something about trust and love.",
      "I attract friendships that feel safe and balanced.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Family & Roots",
    "index": 28,
    "image": 'assets/family.png',
    "affirmations": [
      "I honor where I come from while creating my own path.",
      "My roots give me strength even as I grow in new directions.",
      "Family can be chosen, nurtured, and redefined with love.",
      "I am grateful for the lessons my family taught me — both easy and hard.",
      "I can heal family patterns by living with awareness and care.",
      "I belong to something larger than myself.",
      "I appreciate the generations before me who made my life possible.",
      "I carry forward love and let go of pain.",
      "Home is built from connection, not just blood.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Everyday Abundance",
    "index": 29,
    "image": 'assets/everyday_abundance.png',
    "affirmations": [
      "I already have more than I often notice.",
      "Abundance is not about excess, but about awareness.",
      "There is beauty in the ordinary things surrounding me.",
      "I am rich in experiences, lessons, and love.",
      "Every moment offers something to be grateful for.",
      "I see enoughness in the present, not just in the future.",
      "My life overflows with quiet blessings I once wished for.",
      "I find contentment in what I already hold.",
      "Gratitude multiplies the abundance I see.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Simple Joys",
    "index": 30,
    "image": 'assets/simple_joys.png',
    "affirmations": [
      "Joy doesn’t need to be grand to be real.",
      "Small pleasures have the power to shift my whole day.",
      "I am open to the tiny, fleeting moments that make life beautiful.",
      "Happiness often hides in simplicity.",
      "I allow myself to enjoy without guilt or hurry.",
      "A smile, a scent, a song — each can be a reason to feel alive.",
      "Joy grows when I pause to notice it.",
      "I don’t chase joy; I recognize it when it appears.",
      "The simplest things often hold the deepest meaning.",
    ],
  },
  {
    "isPremium": "1",
    "category": "People & Kindness",
    "index": 31,
    "image": 'assets/people_kindness.png',
    "affirmations": [
      "I am surrounded by people who care, even if quietly.",
      "Acts of kindness, no matter how small, matter deeply.",
      "I can be a source of warmth and compassion wherever I go.",
      "Kindness strengthens both the giver and the receiver.",
      "I appreciate the effort others make to show love.",
      "Every genuine connection reminds me I am not alone.",
      "I choose to meet others with softness, not defense.",
      "The world becomes lighter when I lead with empathy.",
      "Kindness ripples far beyond what I can see.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Nature & the World",
    "index": 32,
    "image": 'assets/nature_world.png',
    "affirmations": [
      "I am part of the living world, not separate from it.",
      "Nature reminds me how to grow, rest, and renew.",
      "The earth supports me in ways I rarely notice.",
      "Each breeze, sunrise, and sound of life is a quiet gift.",
      "I find grounding when I look at the sky or touch the ground.",
      "The natural world teaches me patience and rhythm.",
      "I am grateful for the balance nature shows me each day.",
      "I feel peace when I remember that I belong to the planet, too.",
      "The beauty of the world reflects the beauty within me.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Stress & Anxiety",
    "index": 33,
    "image": 'assets/stress_anxiety.png',
    "affirmations": [
      "I can slow down and take one easy breath.",
      "I am safe in this moment.",
      "My mind can calm even if my thoughts feel loud.",
      "I don’t need to fix everything right now.",
      "I can soften my shoulders and release a little tension.",
      "This feeling will pass.",
      "I can take things one step at a time.",
      "I am allowed to pause and reset.",
      "My body knows how to return to calm.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Handling Failure",
    "index": 34,
    "image": 'assets/handling_failure.png',
    "affirmations": [
      "I learn something valuable every time things don’t go as planned.",
      "I can grow from this, even if it feels hard.",
      "One setback does not define me.",
      "I am allowed to start again.",
      "I am stronger than this moment.",
      "Failure is a part of progress, not the end of it.",
      "I can be kind to myself while I figure things out.",
      "I keep going, even when it’s slow.",
      "I trust myself to rise again.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Confidence",
    "index": 35,
    "image": 'assets/confidence.png',
    "affirmations": [
      "I can handle what comes my way.",
      "I trust myself more every day.",
      "I believe in the skills I am building.",
      "I am capable of steady, quiet courage.",
      "I can make good decisions for myself.",
      "I have done difficult things before.",
      "I deserve to take up space.",
      "I can speak up when it matters.",
      "I am becoming more confident with every small step.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Stop Overthinking",
    "index": 36,
    "image": 'assets/stop_overthinking.png',
    "affirmations": [
      "Not every thought needs my attention.",
      "I can return to the present moment.",
      "I don’t have to solve everything right now.",
      "My thoughts are not always facts.",
      "I can choose a calmer thought.",
      "I am allowed to take a mental break.",
      "I don’t need to replay this again.",
      "I can let this go for now.",
      "I give my mind permission to rest.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest",
    "index": 37,
    "image": 'assets/manifest.png',
    "affirmations": [
      "I attract what I focus on.",
      "I am open to new opportunities.",
      "Good things are making their way toward me.",
      "I am ready to receive what I desire.",
      "I believe I deserve what I dream of.",
      "I trust that my efforts are creating my future.",
      "I am aligning my actions with my goals.",
      "I am becoming the person who can hold the life I want.",
      "I welcome positive change with an open heart.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self-Doubt",
    "index": 38,
    "image": 'assets/self-doubt.png',
    "affirmations": [
      "I am allowed to believe in myself.",
      "I am capable, even when I question myself.",
      "I don’t need to have all the answers to move forward.",
      "I trust my ability to learn and grow.",
      "I am worthy of what I want.",
      "I can take small steps while feeling unsure.",
      "I deserve to feel confident in who I am.",
      "I am more capable than my doubt suggests.",
      "I can give myself permission to try.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Law of Attraction",
    "index": 39,
    "image": 'assets/law_of_attraction.png',
    "affirmations": [
      "I attract what matches my energy.",
      "I am open to receiving abundance.",
      "Life responds to the thoughts I choose.",
      "I welcome experiences that support my growth.",
      "The universe is working with me.",
      "I am aligned with what I desire.",
      "I let go of what blocks my flow.",
      "I trust the timing of my life.",
      "My energy invites the good I seek.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Feel Blessed",
    "index": 40,
    "image": 'assets/feel_blessed.png',
    "affirmations": [
      "I am grateful for the small things that make my life brighter.",
      "I am surrounded by quiet blessings every day.",
      "I appreciate the support I already have.",
      "I recognize the good that is present in my life.",
      "I am thankful for the moments that make me feel alive.",
      "I am blessed in more ways than I remember.",
      "I am open to noticing everyday miracles.",
      "I am grateful for the people who care about me.",
      "My life holds more goodness than I see at first glance.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Find Happiness",
    "index": 41,
    "image": 'assets/find_happiness.png',
    "affirmations": [
      "I can find small joys in my day.",
      "I am learning to create moments of peace.",
      "Happiness can come in simple ways.",
      "I allow myself to feel good.",
      "I am open to joy, even on quiet days.",
      "I deserve moments of happiness.",
      "I can choose one thing today that makes me feel lighter.",
      "I let joy into my life, bit by bit.",
      "I am becoming someone who notices the good.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Practice Gratitude",
    "index": 42,
    "image": 'assets/practice_gratitude.png',
    "affirmations": [
      "I am grateful for the support I already have.",
      "I can find something good in each day.",
      "Gratitude brings me back to what matters.",
      "I appreciate the small moments that lift me up.",
      "I am thankful for the strength that carries me.",
      "I notice the good more each day.",
      "I am grateful for my body and all it does for me.",
      "I can pause and appreciate what is here now.",
      "Gratitude gently changes how I see my life.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Think Positive",
    "index": 43,
    "image": 'assets/think_positive.png',
    "affirmations": [
      "I can choose one positive thought today.",
      "Good things still exist around me.",
      "I can look for what is working, not only what is missing.",
      "A small positive moment can lift my whole day.",
      "I can find light even on slow days.",
      "I am open to seeing the good.",
      "I let in thoughts that support me.",
      "I can shift my mind gently, not forcefully.",
      "Positivity can grow from simple moments.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Enjoy Present",
    "index": 44,
    "image": 'assets/enjoy_present.png',
    "affirmations": [
      "I can slow down and notice this moment.",
      "My mind can rest here, even for a breath.",
      "I don’t need to rush this second.",
      "I can enjoy one small part of today.",
      "I allow myself to be here, right now.",
      "This moment is enough.",
      "I can release the past for a little while.",
      "I can let the future wait.",
      "Presence brings me peace.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Attract Love",
    "index": 45,
    "image": 'assets/attract_love.png',
    "affirmations": [
      "I am worthy of love.",
      "I attract people who value me.",
      "I welcome love that feels safe and kind.",
      "I open my heart gently, at my own pace.",
      "I deserve a love that chooses me.",
      "I attract relationships that support my growth.",
      "Love flows toward me naturally.",
      "I am ready to receive healthy love.",
      "I trust that the right love is on its way.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Cherish People",
    "index": 46,
    "image": 'assets/cherish_people.png',
    "affirmations": [
      "I appreciate the people who stand by me.",
      "I can show love in simple ways.",
      "I value the connections that make me feel understood.",
      "I am grateful for the kindness others give me.",
      "I notice the good people in my life.",
      "I cherish the moments I share with them.",
      "I can be present with the people I love.",
      "I express gratitude for the relationships that support me.",
      "My life is brighter because of the people I care about.",
    ],
  },
  {
    "isPremium": "1",
    "category": "For Couples",
    "index": 47,
    "image": 'assets/for_couples.png',
    "affirmations": [
      "I choose love with patience and understanding.",
      "I communicate with kindness.",
      "I appreciate my partner’s efforts.",
      "Our connection grows through small moments.",
      "I listen with openness and care.",
      "I bring softness into this relationship.",
      "We learn and grow together.",
      "I choose love even when things feel hard.",
      "I create space for closeness.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Forgiveness",
    "index": 48,
    "image": 'assets/forgiveness.png',
    "affirmations": [
      "I allow myself to forgive at my own pace.",
      "I release what no longer serves me.",
      "Forgiveness gives me peace.",
      "I am letting go of old hurt.",
      "I free myself from the weight of resentment.",
      "I choose healing over holding on.",
      "I forgive myself for not knowing better.",
      "I allow space for understanding.",
      "Forgiveness opens my heart.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Overcome Relationships",
    "index": 49,
    "image": 'assets/overcome_relationships.png',
    "affirmations": [
      "I deserve relationships that feel safe.",
      "I can set boundaries that protect my peace.",
      "I do not have to accept treatment that hurts me.",
      "I choose people who value me.",
      "I can walk away when necessary.",
      "I release relationships that drain me.",
      "I am learning what love should feel like.",
      "I allow only respectful connections into my life.",
      "I choose peace over chaos.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Love",
    "index": 50,
    "image": 'assets/love.png',
    "affirmations": [
      "I am open to giving and receiving love.",
      "Love begins with how I treat myself.",
      "I welcome love that feels real and kind.",
      "I allow love to grow naturally.",
      "I am worthy of loving connections.",
      "My heart can heal and open again.",
      "I choose love that honors me.",
      "I attract love that feels peaceful.",
      "Love flows through my life in many forms.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Accept Yourself",
    "index": 51,
    "image": "assets/accept_yourself.png",
    "affirmations": [
      "I accept myself as I am today.",
      "I am learning to embrace my imperfections.",
      "I do not need to be perfect to be worthy.",
      "I am growing at my own pace.",
      "I am enough.",
      "I allow myself to be human.",
      "I accept both my strengths and struggles.",
      "I treat myself with understanding.",
      "I am learning to be on my own side.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Embrace Body",
    "index": 52,
    "image": 'assets/embrace_body.png',
    "affirmations": [
      "My body deserves respect for all it does.",
      "I appreciate my body’s strength and resilience.",
      "I can speak kindly to my body.",
      "My body is not my enemy.",
      "I thank my body for carrying me through life.",
      "I accept my body as it is today.",
      "My body is worthy of care.",
      "I listen to what my body needs.",
      "I honor the person living inside this body.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Embrace Aging",
    "index": 53,
    "image": 'assets/embrace_aging.png',
    "affirmations": [
      "I welcome the wisdom that comes with age.",
      "I honor the years that shaped me.",
      "Aging is a sign of living.",
      "I am grateful for the experiences I have gained.",
      "My heart continues to grow softer and wiser.",
      "I embrace who I am becoming.",
      "Every year teaches me something new.",
      "I age with grace and acceptance.",
      "Each stage of life brings its own beauty.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self Belief",
    "index": 54,
    "image": 'assets/self_belief.png',
    "affirmations": [
      "I believe in my ability to rise.",
      "I trust myself to make good choices.",
      "I can learn whatever I need to learn.",
      "I am capable of creating change.",
      "I believe in my strength.",
      "I trust my inner voice.",
      "I believe I can figure things out.",
      "I trust that I am growing.",
      "I can rely on myself.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self Growth",
    "index": 55,
    "image": 'assets/self_growth.png',
    "affirmations": [
      "I am growing, even when the progress is quiet.",
      "I learn a little every day.",
      "I allow myself to change.",
      "I give myself space to evolve.",
      "I am proud of the person I am becoming.",
      "I grow through challenges and patience.",
      "I welcome growth into my life.",
      "I trust the process of becoming.",
      "I move forward, even in small steps.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self Love",
    "index": 56,
    "image": 'assets/self_love.png',
    "affirmations": [
      "I am learning to love myself.",
      "I deserve my own kindness.",
      "I treat myself with care.",
      "I love the person I am becoming.",
      "I accept myself more each day.",
      "I choose thoughts that support me.",
      "I am gentle with myself.",
      "I am worthy of love from myself too.",
      "I appreciate who I am.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self Care",
    "index": 57,
    "image": 'assets/self_care.png',
    "affirmations": [
      "I deserve rest.",
      "I take time to care for my needs.",
      "I listen to what my mind and body need.",
      "I give myself permission to slow down.",
      "I choose what is healthy for me.",
      "I protect my energy with care.",
      "I make space for my well-being.",
      "I honor my limits.",
      "I take care of myself because I matter.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Mental Health",
    "index": 58,
    "image": 'assets/mental_health.png',
    "affirmations": [
      "My feelings are valid.",
      "I am allowed to struggle and still be worthy.",
      "I deserve support and understanding.",
      "I take my mental health seriously.",
      "I am doing the best I can.",
      "I am learning healthier ways to cope.",
      "I give myself permission to rest.",
      "I check in with myself gently.",
      "I am healing little by little.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Fitness",
    "index": 59,
    "image": 'assets/fitness.png',
    "affirmations": [
      "I am becoming stronger every day.",
      "My body appreciates the effort I put in.",
      "I can show up, even on low-energy days.",
      "Movement is a gift I give to myself.",
      "I am patient with my fitness journey.",
      "I honor my body through movement.",
      "I can take one small step today.",
      "My body gets better with care.",
      "I am proud of my consistency.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Overcome Trauma",
    "index": 60,
    "image": 'assets/overcome_trauma.png',
    "affirmations": [
      "My story is not over.",
      "I am healing piece by piece.",
      "What happened to me is not my fault.",
      "I am safe now.",
      "I give myself permission to heal.",
      "I release the weight I have carried for too long.",
      "I honor my strength in surviving.",
      "I deserve peace.",
      "I am allowed to rebuild.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Stop Addiction",
    "index": 61,
    "image": 'assets/stop_addiction.png',
    "affirmations": [
      "I am stronger than my urges.",
      "I can take this one day at a time.",
      "I choose what supports my future.",
      "I am breaking old patterns.",
      "I forgive myself for past choices.",
      "I am building a healthier life for myself.",
      "I am in control of my actions.",
      "I can ask for help when I need it.",
      "I am proud of every step I take.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Fight Grief",
    "index": 62,
    "image": 'assets/fight_grief.png',
    "affirmations": [
      "It’s okay to feel this deeply.",
      "My grief is a sign of my love.",
      "I am allowed to heal at my own pace.",
      "I carry the memory with tenderness.",
      "I am gentle with myself today.",
      "My heart can hold pain and healing together.",
      "I am not alone in this feeling.",
      "I honor what I lost.",
      "I allow myself to move forward slowly.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Handle Depression",
    "index": 63,
    "image": 'assets/handle_depression.png',
    "affirmations": [
      "I can get through this moment.",
      "I am trying, and that is enough.",
      "I am allowed to rest.",
      "I deserve care and support.",
      "My feelings matter.",
      "I can take small steps toward light.",
      "This heaviness will shift.",
      "I am worthy of help and healing.",
      "I am stronger than I feel right now.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Handle Overthinking",
    "index": 64,
    "image": 'assets/handle_overthinking.png',
    "affirmations": [
      "I can take a break from my thoughts.",
      "Not every thought deserves my attention.",
      "I return to what is real in front of me.",
      "I let go of what I cannot control.",
      "My mind can slow down.",
      "I don’t need to replay this again.",
      "I allow myself to unwind.",
      "I choose one calm thought to hold.",
      "I give my mind permission to rest.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Embrace Failure",
    "index": 65,
    "image": 'assets/embrace_failure.png',
    "affirmations": [
      "Failure is part of learning.",
      "I grow through mistakes.",
      "I can rise again.",
      "I allow myself to start over.",
      "One setback does not define me.",
      "I learn something each time I fall.",
      "I can keep going.",
      "I am proud of my effort.",
      "I trust my ability to improve.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Self Healing",
    "index": 66,
    "image": 'assets/self_healing.png',
    "affirmations": [
      "I am healing step by step.",
      "I give myself space to rest.",
      "I choose what supports my healing.",
      "I am patient with myself.",
      "I release what harms me.",
      "I allow peace into my life.",
      "I am becoming whole again.",
      "My healing matters.",
      "I welcome gentle growth.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Money",
    "index": 67,
    "image": 'assets/manifest_money.png',
    "affirmations": [
      "I attract opportunities that support my growth.",
      "Money flows toward me with ease.",
      "I am worthy of financial stability.",
      "I make choices that support my abundance.",
      "I welcome wealth into my life.",
      "I believe in my ability to earn.",
      "I attract financial blessings.",
      "I increase my income through aligned action.",
      "Prosperity is coming my way.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Friends",
    "index": 68,
    "image": 'assets/manifest_friends.png',
    "affirmations": [
      "I attract people who understand me.",
      "I welcome friendships that feel real and supportive.",
      "I am open to new connections.",
      "I deserve friends who uplift me.",
      "I draw in people who respect me.",
      "I choose friendships that feel safe.",
      "New friendships are on their way.",
      "I attract kind-hearted people.",
      "I am worthy of meaningful friendships.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Love",
    "index": 69,
    "image": 'assets/manifest_love.png',
    "affirmations": [
      "I attract love that feels safe and kind.",
      "I am ready for a healthy relationship.",
      "Love flows toward me naturally.",
      "I deserve a partner who values me.",
      "My heart is open to the right person.",
      "I welcome deep connection.",
      "I attract love that matches my energy.",
      "My soulmate is moving toward me.",
      "I am aligned with the love I want.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Goals",
    "index": 70,
    "image": 'assets/manifest_goals.png',
    "affirmations": [
      "My goals are within reach.",
      "I take small steps toward my dreams.",
      "I stay focused on what matters.",
      "I attract opportunities that help me grow.",
      "My actions create my future.",
      "I believe in my direction.",
      "I am moving closer to my goals each day.",
      "I can achieve what I set my mind to.",
      "I am becoming the person who reaches these goals.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Career",
    "index": 71,
    "image": 'assets/manifest_career.png',
    "affirmations": [
      "I attract career opportunities that fit me.",
      "I am confident in my skills.",
      "I am ready to grow professionally.",
      "I deserve success.",
      "I am becoming the person who thrives in my field.",
      "My career is moving in the right direction.",
      "I attract mentors and opportunities.",
      "I welcome success into my life.",
      "I trust my career path.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Purpose",
    "index": 72,
    "image": 'assets/manifest_purpose.png',
    "affirmations": [
      "I am discovering my purpose day by day.",
      "I trust my inner direction.",
      "I attract clarity and insight.",
      "I am open to what life is showing me.",
      "My purpose becomes clearer as I grow.",
      "I follow what lights me up.",
      "I welcome deeper meaning into my life.",
      "I am aligned with my path.",
      "I trust that I am here for a reason.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Manifest Dreams",
    "index": 73,
    "image": 'assets/manifest_dreams.png',
    "affirmations": [
      "My dreams are possible.",
      "I take steps that move me forward.",
      "I deserve to live the life I imagine.",
      "I am becoming the person who can hold my dreams.",
      "I attract the right opportunities.",
      "I trust the journey toward my vision.",
      "I allow myself to dream boldly.",
      "I believe in what I am creating.",
      "My dreams are already taking shape.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Good Parents",
    "index": 74,
    "image": 'assets/good_parents.png',
    "affirmations": [
      "I am trying my best, and that matters.",
      "I give my child love and safety.",
      "I am patient with myself and my child.",
      "I learn and grow as a parent every day.",
      "I am exactly the parent my child needs.",
      "I can make mistakes and still be a good parent.",
      "I choose love and understanding.",
      "I am present for my child in the ways that count.",
      "I am becoming a better parent with each moment.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Be Mindful",
    "index": 75,
    "image": 'assets/be_mindful.png',
    "affirmations": [
      "I can return to this moment.",
      "I notice what is here without judgment.",
      "I let my breath guide me.",
      "I allow stillness into my day.",
      "I am aware of my thoughts and feelings.",
      "I can pause before reacting.",
      "I give myself permission to slow down.",
      "I bring gentle attention to this moment.",
      "I can be present right now.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Inner Peace",
    "index": 76,
    "image": 'assets/inner_peace.png',
    "affirmations": [
      "I choose peace in small moments.",
      "My calm matters.",
      "I let go of what disturbs my heart.",
      "I return to myself gently.",
      "I welcome ease into my day.",
      "I am learning to soften my mind.",
      "Peace grows within me, little by little.",
      "I am safe within myself.",
      "I allow quietness to fill me.",
    ],
  },
  {
    "isPremium": "1",
    "category": "Let Go",
    "index": 77,
    "image": 'assets/let_go.png',
    "affirmations": [
      "I release what I cannot control.",
      "I let go of what no longer helps me grow.",
      "I am freeing myself from old hurt.",
      "I can loosen my grip and trust the process.",
      "I allow life to move forward.",
      "I let go so I can create space for better.",
      "I release what drains my energy.",
      "I choose peace over holding on.",
      "Letting go is an act of self-care.",
    ],
  },
];

final List<Color> visionColors = [
  const Color(0xFFFFDFDF),
  const Color(0xFFFFF0DE),
  const Color(0xFFE9F4C8),
  const Color(0xFFD8F3D8),
  const Color(0xFFD6F7E7),
  const Color(0xFFD9F5F4),
  const Color(0xFFDAF5FF),
  const Color(0xFFD3E6FE),
  const Color(0xFFE8E5FF),
  const Color(0xFFEFDEFF),
  const Color(0xFFFCDAEE),
  const Color(0xFFFFEBEB),
];

final List<Map<String, dynamic>> visionExamples = [
  {
    "exampleName": "Home & Cozy Lifestyle",
    "items": [
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-1.webp",
        "caption": "Light that makes my home feel alive.",
      },
      {
        "type": "text",
        "text": "Morning sunlight sets a calm tone for the whole day.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-2.webp",
        "caption": "Spaces filled with warmth and softness.",
      },
      {
        "type": "text",
        "text": "A gentle home helps my mind feel steady and supported.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-3.webp",
        "caption": "A bedroom that lets me unwind.",
      },
      {
        "type": "text",
        "text":
            "Rest becomes deeper when my space feels simple and intentional.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-4.webp",
        "caption": "Design that feels calm and grounding.",
      },
      {
        "type": "text",
        "text": "When my environment is clear, my thoughts feel clearer too.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-5.webp",
        "caption": "Quiet moments that make home feel safe.",
      },
      {
        "type": "text",
        "text": "My home holds the small rituals that help me slow down.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-6.webp",
        "caption": "Green corners that bring me back to myself.",
      },
      {
        "type": "text",
        "text": "Nature inside the home softens the atmosphere and softens me.",
      },
      {
        "type": "image",
        "url": "/vision-board/home-lifestyle-7.webp",
        "caption": "Morning rituals that begin gently.",
      },
      {
        "type": "text",
        "text": "The way I start my day shapes the way my mind feels.",
      },
      {
        "type": "text",
        "text":
            "A home that supports my wellbeing — light, calm, warmth, and routines that help my nervous system slow down.",
      },
    ],
  },
  {
    "exampleName": "Self-Worth & Personal Growth",
    "items": [
      {
        "type": "image",
        "url": "/vision-board/self-worth-1.webp",
        "caption": "Becoming someone I’m proud of.",
      },
      {
        "type": "text",
        "text": "Growth starts quietly — in the small moments I choose myself.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-2.webp",
        "caption": "Learning to trust my own voice.",
      },
      {
        "type": "text",
        "text": "My inner voice becomes kinder as I practice listening to it.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-3.webp",
        "caption": "Choosing confidence, gently.",
      },
      {
        "type": "text",
        "text":
            "Confidence isn’t loud, it’s the quiet belief that I deserve good things.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-4.webp",
        "caption": "Showing up as my real self.",
      },
      {
        "type": "text",
        "text": "I feel lighter when I stop shrinking and let myself be seen.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-5.webp",
        "caption": "Letting go of old versions of me.",
      },
      {
        "type": "text",
        "text":
            "I don’t need to hold onto past mistakes. I’m allowed to grow beyond them.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-6.webp",
        "caption": "Learning at my own pace.",
      },
      {
        "type": "text",
        "text": "I grow in seasons, not deadlines, and that’s enough.",
      },
      {
        "type": "image",
        "url": "/vision-board/self-worth-7.webp",
        "caption": "Choosing myself, again and again.",
      },
      {
        "type": "text",
        "text":
            "Self-worth is built through the small choices that honor who I’m becoming.",
      },
      {
        "type": "text",
        "text":
            "I am learning to see myself with gentleness, respect, and the belief that I am enough just as I am.",
      },
    ],
  },
];
